### ISSUE TITLE
file.managed error: is not an absolute path

### ISSUE THREAD

**Issue by martinohansen** [saltstack-formulas/template-formula#126]
Hi,

Im trying to make a new formula based on this template as it seems like a great starting point. Please be aware; this is one of my first formulas and i might be prone to beginner mistakes.

Running this state:
```salt
exabgp-config-file-file-managed:
  file.managed:
    - names:
      - {{ exabgp.config.path }}/{{ exabgp.config.name }}:
        - source: {{ files_switch(['exabgp.conf.jinja']) }}
      - {{ exabgp.env.path }}/{{ exabgp.env.name }}:
        - source: {{ files_switch(['exabgp.env.jinja']) }}
    - mode: 644
    - user: {{ exabgp.user }}
    - group: {{ exabgp.group }}
    - template: jinja
    - require:
      - sls: {{ sls_package_install }}
```

with defaults.yaml:
```yaml
exabgp:
  user: nobody
  group: nobody
  config: 
    path: '/etc/exabgp'
    name: 'exabgp.conf'
  env:
    path: '/etc/exabgp'
    name: 'exabgp.env'
```

Gives me errors like this (with different paths) at the minion:
```salt
----------
          ID: exabgp-config-file-file-managed
    Function: file.managed
        Name: salt://exabgp/files/default/exabgp.env.jinja
      Result: False
     Comment: Specified file salt://exabgp/files/default/exabgp.env.jinja is not an absolute path
     Started: 09:11:22.911320
    Duration: 1.762 ms
     Changes:
----------
```

Let me know if i need to provide more data or a better explanation.

Thanks,
Martin
