### ISSUE TITLE
The case for/against an osarchmap.yaml

### ISSUE THREAD

**Issue by noelmcloughlin** [saltstack-formulas/template-formula#142]
The `osarch` and `kernel` grains are pretty important when handling tarball archives.

Should template-formula provide example for `osarchmap.yaml`?  
Do advantages outweigh any disadvantages?

( A ) **Disadvantages**

- We can simply write `{{ grains.osarch }}` as needed.  
- At least eight formulas switch on grain=osarch in SLS: https://github.com/search?q=org%3Asaltstack-formulas+grains%3Dosarch&type=Code

**proposal for defaults.yaml**
```
  kernel: {{ grains.kernel | lower }}
  arch: {{ grains.osarch }}
```

( B ) **advantages**

- Sometimes the default value is unsuitable.   
- At least four formulas need different value.

https://github.com/saltstack-formulas/consul-formula/blob/9324564cdf5cbf78bd881322571529c4e8c53673/consul/map.jinja

https://github.com/saltstack-formulas/nomad-formula/blob/1060beada2fb0e06781abfe2f4cf1e2957e780a4/nomad/map.jinja

https://github.com/saltstack-formulas/kibana-formula/blob/c2b8c2c91f021a75a7cbdb432f09945e2437ccf0/kibana/source.sls

https://github.com/saltstack-formulas/node-formula/blob/fdbcde9daf7dba218a47853656ef4a1ecce0704e/node/binary.sls

**proposal for defaults.yaml**
```
  kernel: {{ grains.kernel | lower }}
```

**proposal for osarchmap.yaml**
```
# -*- coding: utf-8 -*-
# vim: ft=yaml
#
# Setup variables using grains['osarch'] based logic.
# You just need to add the key:values for an `osarch` that differ
# from `defaults.yaml` + `os_family.yaml`.
# Only add an `osarch` which is/will be supported by the formula
#
# If you do not need to provide defaults via the `osarch` grain,
# you will need to provide at least an empty dict in this file, e.g.
# osarch: {}
---
amd64:
  arch: amd64

x86_64:
  arch: amd64

386:
  arch: 386

arm64:
  arch: arm64

armv6l:
  arch: armv6l

armv7l:
  arch: armv6l

ppc64le:
  arch: ppc64le

s390x:
  arch: s390x
```

I can raise a PR once we have guidance on what people prefer.
