### ISSUE TITLE
[discussion] retry internet-depending states

### ISSUE THREAD

**Issue by noelmcloughlin** [saltstack-formulas/template-formula#145]
For internet dependent states we could add `retrys` support per https://docs.saltstack.com/en/latest/ref/states/requisites.html#retrying-states

This could be a macro (See #134)

Example: https://github.com/saltstack-formulas/packages-formula/pull/55

**Comment by myii** [comment]
Something to consider: https://github.com/saltstack-formulas/packages-formula/pull/55#issuecomment-505413561.

**Comment by noelmcloughlin** [comment]
This proposal emerged at https://github.com/saltstack-formulas/packages-formula/pull/55

Declaration
```
  retry_option:
    # https://docs.saltstack.com/en/latest/ref/states/requisites.html#retrying-states
    attempts: 5
    until: True
    interval: 30
    splay: 20
```

Usage:
```
    - retry: {{ packages.retry_option|json }}
```
