### ISSUE TITLE
Add link to official documentation in default pillar

### ISSUE THREAD

**Issue by n-rodriguez** [saltstack-formulas/template-formula#176]
It could be nice to add a pillar key with the link to the official documentation so it could be retrieved within Salt to generate documentation.

Like: 
```yml
---
rkhunter:
  doc_link: http://rkhunter.sourceforge.net/
```

Of course it should not be used in the configuration itself, but it could be added in TOFS templates.

**Comment by n-rodriguez** [comment]
@myii WDYT?

**Comment by myii** [comment]
@n-rodriguez Sounds like a nice idea.  I reckon @noelmcloughlin would have a nice suggestion about the YAML nesting.  My guess would be something like:

```yaml
---
rkhunter:
  upstream:
    main_page: http://rkhunter.sourceforge.net/
    docs: http://rkhunter.sourceforge.net/
    ...
```

Probably best to have it in `defaults.yaml`.
