### ISSUE TITLE
How to add multiple sub config files

### ISSUE THREAD

**Issue by wrender** [saltstack-formulas/template-formula#190]
I tried reading the documentation but can't seem to find info on this; Does this template allow for supporting multiple subconfig files?  For example I have an application I am trying to make a community formula for that has one main config, and then a bunch of other config files like this:

```
nifi:
  pkg:
    name: myapp
  rootgroup: root
  config: '/etc/myapp'
  service:
    name: myapp
  subcomponent:
    config1: '/etc/myapp-subcomponent1-formula.conf'
    config2: '/etc/myapp-subcomponent2-formula.conf'
    config3: '/etc/myapp-subcomponent3-formula.conf'
    config4: '/etc/myapp-subcomponent4-formula.conf'
    config5: '/etc/myapp-subcomponent5-formula.conf'
  # Just here for testing
  added_in_defaults: defaults_value
  winner: defaults
```
