### ISSUE TITLE
Establish `template-formula` as the go-to resource for all formula development

### ISSUE THREAD

**Issue by myii** [saltstack-formulas/template-formula#21]
This issue is a collection of ideas taken from the [log of discussions](https://github.com/saltstack-formulas/template-formula/wiki/%5B2019-02-08%5D-Log:-Initial-improvements'-discussions) captured in the wiki.

- [x] Update to new `map.jinja` style -- #20.
- [x] Switch to the TOFS pattern (`files_switch`) -- #19.
- [ ] Add documentation: guides, proposals, etc. -- use the `template-formula` wiki the central location for planning/organisation/reference.
- [ ] Add a test scaffold with `kitchen-ci` and `inspec` (or `testinfra`) examples for the basic tasks (add/remove package, check service, etc).
- [ ] Add the remove state advocated by @noelmcloughlin.
- [ ] Make the formula "actually functional" so that all parts can be run, to aid understanding and quality assurance.
- [ ] Investigate how the TOFS pattern can be used to mitigate the use of `formula:ng` states — most of those can be integrated and removed and only keep one formula.
- [ ] Make this `template-formula` a sticky formula for the whole SaltStack Formulas project.
- [ ] Adapt `template-formula` to not be too focussed on `pkg` -- must also consider tarball releases, github repos, etc.
- [ ] Add a `macros.jinja` template with common macros that "Any formulae would find useful" -- repeatable patterns deserve repeatable code.
- [ ] Ensure that each file does only one thing and do it well (instead of monolithic files), e.g. `pkg/install.sls`, `pkg/clean.sls`, `repo/install.sls`, `repo/clean.sls`, etc.
- [ ] Evaluate #18 to see if it can be merged into this issue.

**Comment by daks** [comment]
Just an idea: document how to create a formula from this template one, inside this repository or/and in saltstack docs

**Comment by myii** [comment]
@daks I've added that to the task list above -- thanks for that suggestion.

**Comment by alxwr** [comment]
@myii I just wanted to say „Thank you!“ :-)
This formula enabled me to implement https://github.com/saltstack-formulas/prometheus-formula _really_ fast. I found the structure and especially your turnkey Travis/kitchen configuration_very_ helpful.

**Comment by myii** [comment]
@alxwr That's really good to hear and it makes all of this effort worthwhile.  There were lots of contributions involved, including your own!  Good to see that you've got `semantic-release` running as well.

We've got an upcoming issue due to wanting to implement `config.get` properly, instead of `pillar.get`.  The only solution I've been able to find so far is using `defaults.merge` so I'm going to submit a PR in order to open up discussion.  Since you're familiar with `salt-ssh`, I'll request a review from you as well, so that you have the opportunity to argue against my proposal!  Actually, the alternative is to go back to `pillar.get` and that may be the final conclusion anyway...

**Comment by alxwr** [comment]
@myii AFAIR we could work around the `defaults.merge` issue, because we can detect whether `salt` or `salt-ssh` is used. But this is not pretty. :-)
Maybe it's time for a `libworkaround.jinja` which would be living documentation of several incompatibilities and shortcomings that need to go. :-)

**Comment by myii** [comment]
@alxwr So there's a reliable way to check for `salt-ssh`?  That's excellent news.  So we can have both methods of merging the map available and then no-one loses out.  Do you mind sharing it here?  Then I can include it in the PR immediately, so that everyone can get on with reviewing it, rather than having a long discussion first.  I will ensure that you are credited as the author of that specific commit, identifying between `salt` and `salt-ssh`.

**Comment by alxwr** [comment]
@myii Sry for the delay.:-)
The way I found most straightforward, is inserting `grains:salt_ssh: True` in the `roster` file. But I get, that this is not exactly portable.

The second most reliable way is to compare paths:

`salt host grains.itms`:

```yaml
    pythonpath:                                                                                                                                                                               
        - /usr/local/bin                                                                                                                                                                      
        - /usr/local/lib/python36.zip                                                                                                                                                         
        - /usr/local/lib/python3.6                                                                                                                                                            
        - /usr/local/lib/python3.6/lib-dynload                                                                                                                                                
        - /usr/local/lib/python3.6/site-packages
    saltpath:
        /usr/local/lib/python3.6/site-packages/salt
```

`salt-ssh host2 grains.itms`:

```yaml
    pythonpath:                                                                                                                                                                               
        - /var/tmp/.root_99b0b6_salt/py3                                                                                                                                                      
        - /var/tmp/.root_99b0b6_salt/pyall                                                                                                                                                    
        - /var/tmp/.root_99b0b6_salt                                                                                                                                                          
        - /usr/lib/python35.zip                                                                                                                                                               
        - /usr/lib/python3.5                                                                                                                                                                  
        - /usr/lib/python3.5/plat-x86_64-linux-gnu                                                                                                                                            
        - /usr/lib/python3.5/lib-dynload                                                                                                                                                      
        - /usr/local/lib/python3.5/dist-packages                                                                                                                                              
        - /usr/lib/python3/dist-packages
    saltpath:                                                                                                                                                                                 
        /var/tmp/.root_99b0b6_salt/pyall/salt
```

`salt-ssh` is run from a temporary directory on the minion. This shows in the grain `saltpath`. (We could also correlate `pythonpath[0]` with `saltpath` for higher certainty, but I think focusing on `saltpath` is sufficient.)
