### ISSUE TITLE
[FEATURE]   Use dynamic values in Inspec tests instead of hardcoded

### ISSUE THREAD

**Issue by noelmcloughlin** [saltstack-formulas/template-formula#242]
### Is your feature request related to a problem?

I am writing some **Inspec** tests using saltstack-formulas as a reference and the hard coding of values is anti-pattern which I'm trying to solve.  I want to move hard coded values from Inspec Ruby files to YAML and import them dynamically.  When something changes I want to update `test\vars.yaml` instead of Ruby strings.   Consider two files here:

**config/vars.yaml:**
```
   # values as configuration data
   configured:
       name: dos2unix`
       binary_name: /usr/bin/dos2unix
      .. etc ..
```
**test/vals.yaml:**
  ```
    #  values for testing suites
    expecting:
       package_name: dos2unix
       binary_name: /usr/bin/dos2unix
      .. etc ..
``` 
After some tests, the [Ruby YAML module](https://github.com/ruby/yaml#usage) is good solution I think. 
 We do not need to hard code values as ruby strings if test data is separated from tests.

```
# frozen_string_literal: true

require 'yaml'
expect = YAML.load_file("test/vals.yaml")['expecting']

control 'package install' do
   impact 1.0
   title 'verify package #{expect(package_name}  is installed'

  describe package(expect['package_name']) do
     it { should be_installed }
 end
end
```

I think this could work in saltstack-formluas so just raising for discussion.

### Describe the solution you'd like

I think this idea will work well in saltstack-formulas too.

### Describe alternatives you've considered

I'm using similar pattern using Molecule (ansible verifier) and trying to reuse the pattern with Inspec Verifier
